name: Node

on: 
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master
  

jobs:
  UnitTest_Coverage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm test
      run: |
        npm ci
        npm run test:cov
      env:
        CI: true
